allow-other: true

logging:
  level: log_debug
  file-path: "blobfuse2-logs.txt"
  type: base

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 0
  entry-expiration-sec: 0
  negative-entry-expiration-sec: 0
  ignore-open-flags: true

file_cache:
  path: "./myazurecontainercache"
  timeout-sec: 30
  max-size-mb: 10
  allow-non-empty-temp: true
  cleanup-on-start: true

attr_cache:
  timeout-sec: 30

azstorage:
  type: "block"
  account-name: ""
  container: ""
  account-key: ""
  mode: key
  endpoint: ""